version: "3.7"
services:
  pocketbase:
    image: mussingtonr/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    expose:
      - "8090"
    volumes:
      - "/etc/dokploy/templates/${HASH}/pb_data:/pb_data"
      - "/etc/dokploy/templates/${HASH}/pb_migrations:/pb_migrations"
      - "/etc/dokploy/templates/${HASH}/pb_hooks:/pb_hooks"
      - "/etc/dokploy/templates/${HASH}/pb_public:/pb_public"
    environment:
      - TZ=America/New_York
      # See docker-compose.example.yml for all available environment variables